#!/usr/bin/env python3
"""T00.01 — transcribe Repo 1 Appendix E + §39 into errors/.

Sources (normative, in precedence order):
  - Repo 1 Appendix E        error code -> HTTP status, retry class, meaning
  - Repo 1 §39               retry class -> client/worker behavior
  - Repo 1 §26.1             the problem-document type URI template
  - Repo 2 Appendix G        error code -> user-facing UX class and behavior

Codes absent from Repo 2 Appendix G are administrative or internal surfaces
that the webmail client never renders; their ux_class is null. That is a
transcription outcome, not an omission.
"""

import re
import sys
import os

sys.path.insert(0, os.path.dirname(__file__))
import specmd

TYPE_URI_TEMPLATE = "https://errors.karyalay.in/mail/{code}"


def parse_appendix_e(repo1):
    body = specmd.section(repo1, "Appendix E — Error Catalog")
    rows = specmd.rows_as_dicts(specmd.table(body))
    out = []
    for row in rows:
        out.append(
            {
                "code": row["Code"],
                "http_status": int(row["HTTP"]),
                "retry_class": row["Retry class"],
                "meaning": row["Meaning"],
            }
        )
    return out


def parse_retry_classes(repo1):
    body = specmd.section(repo1, "39 Error Catalog and Failure Semantics")
    rows = specmd.rows_as_dicts(specmd.table(body))
    return [
        {"name": row["Retry class"], "client_behavior": row["Client/worker behavior"]}
        for row in rows
    ]


def parse_appendix_g(repo2):
    """Repo 2 keys some rows by several codes joined with ' / '."""
    body = specmd.section(repo2, "Appendix G. Error-to-UX Mapping Catalog")
    rows = specmd.rows_as_dicts(specmd.table(body))
    mapping = {}
    for row in rows:
        for code in [c.strip() for c in row["Server code"].split("/")]:
            mapping[code] = {
                "ux_class": row["UX class"],
                "ux_behavior": row["Required behavior"],
            }
    return mapping


def family(code):
    """Bounded metrics label required by Repo 1 §40.3.

    Purely mechanical: the first underscore-delimited segment of the code.
    No per-code judgement is applied, so the value can never drift from the
    catalog it is derived from.
    """
    return code.split("_")[0]


def main():
    repo1 = specmd.read_spec("repo1")
    repo2 = specmd.read_spec("repo2")

    errors = parse_appendix_e(repo1)
    retry_classes = parse_retry_classes(repo1)
    ux = parse_appendix_g(repo2)

    known_classes = {c["name"] for c in retry_classes}
    seen = set()
    for err in errors:
        if err["code"] in seen:
            sys.exit("duplicate code in Appendix E: %s" % err["code"])
        seen.add(err["code"])
        if err["retry_class"] not in known_classes:
            sys.exit(
                "Appendix E uses retry class %r that §39 does not define (code %s)"
                % (err["retry_class"], err["code"])
            )
        err["family"] = family(err["code"])
        err["type"] = TYPE_URI_TEMPLATE.format(code=err["code"])
        mapped = ux.get(err["code"])
        err["ux_class"] = mapped["ux_class"] if mapped else None
        err["ux_behavior"] = mapped["ux_behavior"] if mapped else None

    unknown_ux = sorted(set(ux) - seen)
    if unknown_ux:
        sys.exit(
            "Repo 2 Appendix G references codes absent from Appendix E: %s\n"
            "Raise an ADR (Master §0.2); do not add them here." % ", ".join(unknown_ux)
        )

    catalog = {
        "contract": "karyalay-mail-contracts/errors",
        "contract_version": "0.1.0",
        "type_uri_template": TYPE_URI_TEMPLATE,
        "sources": {
            "codes": "karyalay-mail repository-spec-v1.0 Appendix E",
            "retry_classes": "karyalay-mail repository-spec-v1.0 §39",
            "type_uri": "karyalay-mail repository-spec-v1.0 §26.1",
            "ux_classes": "karyalay-webmail repository-spec-v1.0 Appendix G",
        },
        "retry_classes": retry_classes,
        "errors": errors,
    }
    header = (
        "Karyalay Mail — error catalog v1\n"
        "\n"
        "GENERATED by tools/derive/gen_errors.py. Do not hand-edit.\n"
        "Transcribed from karyalay-mail repository-spec-v1.0 Appendix E and §39,\n"
        "and karyalay-webmail repository-spec-v1.0 Appendix G.\n"
        "Filename fixed by Master Contract §0.3.\n"
        "Validated against errors/error-catalog-v1.schema.json."
    )
    path = specmd.write_yaml("errors/error-catalog-v1.yaml", catalog, header)
    print("wrote %s (%d codes, %d retry classes, %d with a UX class)"
          % (path, len(errors), len(retry_classes),
             sum(1 for e in errors if e["ux_class"])))


if __name__ == "__main__":
    main()
